# Generated by Django 4.2.9 on 2024-05-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_poll_option_one_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='option_one_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_three_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_two_count',
            field=models.IntegerField(default=0),
        ),
    ]
