# Generated by Django 4.2.9 on 2024-05-19 01:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
